apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-access
  namespace: default
subjects:
- kind: Deployment
  name:  chiron-client
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pod-access
  apiGroup: rbac.authorization.k8s.io